In [1]:
import pandas as pd
import glob
import os

# Caminho da pasta onde estão os CSVs
pasta = r'C:\Projetos Python\WebScraping_SofaScore\data\outputs\silver\2025-04-28_14-41-41\Matches'

# Pega todos os arquivos CSV da pasta
arquivos_csv = glob.glob(os.path.join(pasta, '*.csv'))

# Lê todos os CSVs e armazena numa lista de DataFrames
lista_df = [pd.read_csv(arquivo) for arquivo in arquivos_csv]

# Concatena todos os DataFrames um abaixo do outro
df = pd.concat(lista_df, ignore_index=True)

# Exibe o resultado
df

,season_id_round_slug,unique_tournament_id,season_id,round,slug,tournament_name,match_id,cup_round_type,match_slug,match_timestamp,match_datatime,home_team_id,home_team_name,home_score,away_score,away_team_name,away_team_id
0,571201,10294,57120,1,NaN,Alagoano,11888632,NaN,cse-murici,1705777200,2024-01-20 16:00:00-03:00,49195,Murici,2.0,1.0,CSE,336565
1,571201,10294,57120,1,NaN,Alagoano,11888631,NaN,sc-penedense-crb,1705777200,2024-01-20 16:00:00-03:00,477783,SC Penedense,0.0,1.0,CRB,22032
2,571201,10294,57120,1,NaN,Alagoano,11888628,NaN,cruzeiro-al-asa,1705863600,2024-01-21 16:00:00-03:00,2019,ASA,2.0,1.0,Cruzeiro-AL,405931
3,571201,10294,57120,1,NaN,Alagoano,11888629,NaN,aa-coruripe-csa,1705867200,2024-01-21 17:00:00-03:00,2010,CSA,1.0,0.0,AA Coruripe,21847
4,571202,10294,57120,2,NaN,Alagoano,11888625,NaN,cruzeiro-al-csa,1706131800,2024-01-24 18:30:00-03:00,405931,Cruzeiro-AL,0.0,2.0,CSA,2010
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2165,569749,92,56974,9,NaN,Carioca Série A – Taça Guanabara,11873087,NaN,vasco-da-gama-botafogo,1708282800,2024-02-18 16:00:00-03:00,1958,Botafogo,2.0,4.0,Vasco da Gama,1974
2166,569749,92,56974,9,NaN,Carioca Série A – Taça Guanabara,11873084,NaN,portuguesa-rj-volta-redonda,1708290600,2024-02-18 18:10:00-03:00,6982,Volta Redonda,1.0,1.0,Portuguesa-RJ,208067
2167,569749,92,56974,9,NaN,Carioca Série A – Taça Guanabara,11873085,NaN,audax-rj-nova-iguacu,1708302600,2024-02-18 21:30:00-03:00,85341,Audax-RJ,1.0,2.0,Nova Iguaçu,6981
2168,569749,92,56974,9,NaN,Carioca Série A – Taça Guanabara,11873082,NaN,sampaio-correa-rj-bangu-atletico-clube,1708454700,2024-02-20 15:45:00-03:00,257632,Sampaio Corrêa-RJ,2.0,0.0,Bangu Atlético Clube,1993
2169,569749,92,56974,9,NaN,Carioca Série A – Taça Guanabara,11873083,NaN,boavista-flamengo,1708475400,2024-02-20 21:30:00-03:00,5981,Flamengo,4.0,0.0,Boavista,6977

In [2]:
df[df['match_id'] == 11874767]

,season_id_round_slug,unique_tournament_id,season_id,round,slug,tournament_name,match_id,cup_round_type,match_slug,match_timestamp,match_datatime,home_team_id,home_team_name,home_score,away_score,away_team_name,away_team_id
396,570061,11682,57006,1,NaN,"Brasiliense, Série A",11874767,NaN,planaltina-ec-gama,1705185000,2024-01-13 19:30:00-03:00,1978,Gama,2.0,0.0,Planaltina EC,394962